services:
  mmysql:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas1234
    ports:
      - "3308:3306"
    networks:
      - spring_mysql

  spring-boot-app:
    container_name: springbootapp
    build: .
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - mmysql
    environment:
      MYSQL_HOST: mmysql
      MYSQL_USER: lucas
      MYSQL_PASSWORD: lucas1234
      MYSQL_PORT: 3306
    networks:
      - spring_mysql
networks:
  spring_mysql:
    driver: bridge